[2024-03-27T03:23:17.286+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Process_W3_Data.RemoveHash manual__2024-03-27T03:23:06.779624+00:00 [queued]>
[2024-03-27T03:23:17.306+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Process_W3_Data.RemoveHash manual__2024-03-27T03:23:06.779624+00:00 [queued]>
[2024-03-27T03:23:17.309+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-27T03:23:17.343+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): RemoveHash> on 2024-03-27 03:23:06.779624+00:00
[2024-03-27T03:23:17.362+0000] {standard_task_runner.py:60} INFO - Started process 119 to run task
[2024-03-27T03:23:17.370+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Process_W3_Data', 'RemoveHash', 'manual__2024-03-27T03:23:06.779624+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/w3c.py', '--cfg-path', '/tmp/tmp4fiia4f0']
[2024-03-27T03:23:17.385+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask RemoveHash
[2024-03-27T03:23:17.541+0000] {task_command.py:423} INFO - Running <TaskInstance: Process_W3_Data.RemoveHash manual__2024-03-27T03:23:06.779624+00:00 [running]> on host 94418fe46b42
[2024-03-27T03:23:17.754+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Process_W3_Data' AIRFLOW_CTX_TASK_ID='RemoveHash' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T03:23:06.779624+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-27T03:23:06.779624+00:00'
[2024-03-27T03:23:17.765+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/w3c.py", line 81, in ListFiles
    arr=os.listdir(RawFiles)
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/data/Raw/'
[2024-03-27T03:23:17.798+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Process_W3_Data, task_id=RemoveHash, execution_date=20240327T032306, start_date=20240327T032317, end_date=20240327T032317
[2024-03-27T03:23:17.832+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task RemoveHash ([Errno 2] No such file or directory: '/home/airflow/gcs/data/Raw/'; 119)
[2024-03-27T03:23:17.872+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-27T03:23:17.949+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
