[2024-03-27T20:20:29.735+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Process_W3_Data.remove_hash manual__2024-03-27T20:20:23.958457+00:00 [queued]>
[2024-03-27T20:20:29.747+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Process_W3_Data.remove_hash manual__2024-03-27T20:20:23.958457+00:00 [queued]>
[2024-03-27T20:20:29.748+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-27T20:20:29.769+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): remove_hash> on 2024-03-27 20:20:23.958457+00:00
[2024-03-27T20:20:29.779+0000] {standard_task_runner.py:60} INFO - Started process 232 to run task
[2024-03-27T20:20:29.784+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Process_W3_Data', 'remove_hash', 'manual__2024-03-27T20:20:23.958457+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/w3c.py', '--cfg-path', '/tmp/tmp0kgtz79l']
[2024-03-27T20:20:29.788+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask remove_hash
[2024-03-27T20:20:29.882+0000] {task_command.py:423} INFO - Running <TaskInstance: Process_W3_Data.remove_hash manual__2024-03-27T20:20:23.958457+00:00 [running]> on host d9bdcddb4bab
[2024-03-27T20:20:29.995+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Process_W3_Data' AIRFLOW_CTX_TASK_ID='remove_hash' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T20:20:23.958457+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-27T20:20:23.958457+00:00'
[2024-03-27T20:20:30.000+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/w3c.py", line 66, in ListFiles
    arr=os.listdir(RawFiles)
NameError: name 'RawFiles' is not defined
[2024-03-27T20:20:30.020+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Process_W3_Data, task_id=remove_hash, execution_date=20240327T202023, start_date=20240327T202029, end_date=20240327T202030
[2024-03-27T20:20:30.041+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task remove_hash (name 'RawFiles' is not defined; 232)
[2024-03-27T20:20:30.079+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-27T20:20:30.118+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
